BASE_PROMPT = (
"I need assistance in producing AI-generated text that I convert to music using MIDI files."
" Initially, I'll provide a description of the format I need for the textual representation of the music. "
" Since music is a time-based art form, the notes follow each other in time, and sometimes there are no chords, that is, silences. "
" The way I would like you to generate them is as follows:"
" I need assistance in creating AI-generated text that will be converted into MIDI chord sequences."
" The format for the textual representation of these chords is crucial and must be strictly adhered to for successful conversion into MIDI format."
" Each chord is represented as a tuple, where each element of the tuple represents a chord made up of multiple notes, and the duration of the chord."
" The format should be: chord_pitch_duration_data = [((note1, note2, ...), duration), ((note1, note2, note3), duration), ...]"
" The notes in each chord are to be represented by integer values, ranging from 21 (A0 - 27.50 Hz) to 96 (C7 - 2093 Hz)."
" These numbers are MIDI note numbers and should be used to represent each note in the chord."
" The duration of each chord is a float value, which can range from 0 to 2, with the same representations as previously described for melodies:"
" 0.125 for an eighth note, 0.25 for a quarter note, 0.5 for a half note, 1 for a whole note, 2 for a double whole note, etc."
" Creative durations like 0.29 or 1.22 are also acceptable."
" In the sequence, when a chord is meant to represent a silence, use the note value of 0, and the duration will indicate the length of the silence."
" Here are some key aspects to consider in chord progression:"
" Harmony: Each chord should harmonically complement the others, maintaining a sense of musical coherence."
" Progression: The sequence of chords should tell a musical story, with a clear beginning, development, and resolution."
" Variety: Use a mix of chord types (major, minor, diminished, etc.) and inversions to add interest."
" Rhythm: The rhythm of the chord progression, indicated by the durations, should be engaging and varied."
" For example, a simple progression in C major might start with a C major chord, followed by an F major chord, then a G major chord, and finally returning to C major."
"Remember, the format of the output is critical. It must start with [, contain pairs of tuples in the format ((note1, note2, ...), duration), and end with ]. Any deviation from this format will result in an error in the MIDI conversion process."
"With these guidelines in mind, could you generate a chord progression in the specified format, considering the principles of harmony, progression, variety, and rhythm?"

)